export const photosConstants = {
	SEARCH_PHOTOS_BY_TAG_REQUEST: 'SEARCH_PHOTOS_BY_TAG_REQUEST',
	SEARCH_PHOTOS_BY_TAG_SUCCESS: 'SEARCH_PHOTOS_BY_TAG_SUCCESS',
	SEARCH_PHOTOS_BY_TAG_FAILURE: 'SEARCH_PHOTOS_BY_TAG_FAILURE'
};
